### ISSUE TITLE
Show relative paths images from the README

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#9]
Implement markdown parsing npm uses.

**Comment by zbranzov** [comment]
It doesn't seem to work on uat because of sync fail:

INFO: syncing from 0 to 10

09:55:13
/var/app/current/src/dist/server.js:307069 throw error; ^
/var/app/current/src/dist/server.js:307069
throw error;
^

09:55:13
Error: Cannot open /codebuild/output/src535373142/src/node_modules/oniguruma/build/Release/onig_scanner.node: Error: /codebuild/output/src535373142/src/node_modules/oniguruma/build/Release/onig_scanner.node: cannot open shared object file: No such file or directory at Object.<anonymous> (/var/app/current/src/dist/server.js:279333:194) at Object.getOwnPropertySymbols (/var/app/current/src/d
Error: Cannot open /codebuild/output/src535373142/src/node_modules/oniguruma/build/Release/onig_scanner.node: Error: /codebuild/output/src535373142/src/node_modules/oniguruma/build/Release/onig_scanner.node: cannot open shared object file: No such file or directory
at Object.<anonymous> (/var/app/current/src/dist/server.js:279333:194)
at Object.getOwnPropertySymbols (/var/app/current/src/dist/server.js:279334:30)
at __webpack_require__ (/var/app/current/src/dist/server.js:20:30)
at Object.<anonymous> (/var/app/current/src/dist/server.js:152160:35)
at __webpack_require__ (/var/app/current/src/dist/server.js:20:30)
at Object.<anonymous> (/var/app/current/src/dist/server.js:92535:16)
at Object.<anonymous> (/var/app/current/src/dist/server.js:92905:4)
at __webpack_require__ (/var/app/current/src/dist/server.js:20:30)
at Object.<anonymous> (/var/app/current/src/dist/server.js:218032:13)
at Object.<anonymous> (/var/app/current/src/dist/server.js:218288:4)

After synced locally still no new parser features are available.
